/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/donut48.gltf')

  const [colour, setColour] = useState("#ED91AD")

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Donut.geometry} material={nodes.Donut.material} position={[-0.0037, 0.0251, -0.0048]}>
        <mesh onClick={()=>{ colour==="#ED91AD" ? setColour("#93c572") : setColour("#ED91AD")}} geometry={nodes.Icing.geometry} material={nodes.Icing.material} material-color={colour}/>
      </mesh>
      <mesh
        geometry={nodes.SurfSphere001.geometry}
        material={nodes.SurfSphere001.material}
        position={[0.0619, 0.0463, -0.014]}
        rotation={[0.8888, -0.848, 2.0698]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere002.geometry}
        material={nodes.SurfSphere002.material}
        position={[0.0455, 0.0489, -0.0474]}
        rotation={[1.2366, -0.8422, 0.2755]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere003.geometry}
        material={nodes.SurfSphere003.material}
        position={[-0.0369, 0.0578, 0]}
        rotation={[1.5419, 0.0935, -1.6736]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere004.geometry}
        material={nodes.SurfSphere004.material}
        position={[-0.0168, 0.0444, 0.0192]}
        rotation={[0.4798, -0.6611, -2.6804]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere005.geometry}
        material={nodes.SurfSphere005.material}
        position={[0.006, 0.0464, 0.0631]}
        rotation={[2.1717, -0.3312, 2.656]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere006.geometry}
        material={nodes.SurfSphere006.material}
        position={[0.0451, 0.0528, 0.0188]}
        rotation={[1.557, 0.0816, 1.6277]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere007.geometry}
        material={nodes.SurfSphere007.material}
        position={[0.0331, 0.0498, -0.0047]}
        rotation={[2.1411, 0.9975, -0.713]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere008.geometry}
        material={nodes.SurfSphere008.material}
        position={[0.0577, 0.05, -0.0009]}
        rotation={[1.7975, -0.3592, 1.8933]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere009.geometry}
        material={nodes.SurfSphere009.material}
        position={[0.0481, 0.0518, 0.0159]}
        rotation={[1.6056, -0.1126, -0.9562]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere010.geometry}
        material={nodes.SurfSphere010.material}
        position={[-0.005, 0.058, 0.0398]}
        rotation={[1.4318, 0.3728, -0.3626]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere011.geometry}
        material={nodes.SurfSphere011.material}
        position={[-0.0271, 0.0533, 0.0211]}
        rotation={[1.2658, -0.534, -3.0637]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere012.geometry}
        material={nodes.SurfSphere012.material}
        position={[-0.0279, 0.0519, 0.0162]}
        rotation={[1.1489, -1.0095, 2.0955]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere013.geometry}
        material={nodes.SurfSphere013.material}
        position={[-0.0584, 0.0443, 0.0323]}
        rotation={[2.0354, 1.1292, 0.1727]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere014.geometry}
        material={nodes.SurfSphere014.material}
        position={[-0.061, 0.0518, 0.0063]}
        rotation={[1.4442, 0.4798, 3.0001]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere015.geometry}
        material={nodes.SurfSphere015.material}
        position={[-0.0436, 0.0587, -0.0174]}
        rotation={[1.6858, -0.1431, -1.9136]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere016.geometry}
        material={nodes.SurfSphere016.material}
        position={[-0.0409, 0.0593, -0.0206]}
        rotation={[1.7013, 0.283, -0.8613]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere017.geometry}
        material={nodes.SurfSphere017.material}
        position={[-0.0214, 0.0604, -0.0225]}
        rotation={[2.4189, -0.4316, -2.4597]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere018.geometry}
        material={nodes.SurfSphere018.material}
        position={[-0.0434, 0.0529, -0.0419]}
        rotation={[0.6431, 0.9769, -0.1616]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere019.geometry}
        material={nodes.SurfSphere019.material}
        position={[-0.0107, 0.0598, -0.043]}
        rotation={[1.2729, -0.6548, -0.1075]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere020.geometry}
        material={nodes.SurfSphere020.material}
        position={[0.0185, 0.0535, -0.0599]}
        rotation={[1.2265, -0.0845, 1.671]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.SurfSphere021.geometry}
        material={nodes.SurfSphere021.material}
        position={[0.0419, 0.0545, -0.0463]}
        rotation={[0.7907, -0.191, 0.7247]}
        scale={[0.2261, 0.2592, 0.2496]}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={nodes.Sphere006.material}
        position={[0.0236, 0.0522, -0.0609]}
        rotation={[0.7625, 0.1132, -2.6462]}
        scale={[0.0454, 0.1002, 0.0491]}
      />
      <mesh
        geometry={nodes.Sphere008.geometry}
        material={nodes.Sphere008.material}
        position={[-0.0367, 0.0509, -0.0516]}
        rotation={[0.3878, 0.3158, 0.2269]}
        scale={[0.0454, 0.1002, 0.0491]}
      />
      <mesh
        geometry={nodes.Sphere009.geometry}
        material={nodes.Sphere009.material}
        position={[-0.0536, 0.051, -0.0306]}
        rotation={[1.5261, 0.8997, 2.2641]}
        scale={[0.0454, 0.1002, 0.0491]}
      />
      <mesh
        geometry={nodes.Sphere015.geometry}
        material={nodes.Sphere015.material}
        position={[0.028, 0.0543, 0.0464]}
        rotation={[1.3497, -0.266, 0.083]}
        scale={[0.0454, 0.1002, 0.0491]}
      />
      <mesh
        geometry={nodes.Sphere016.geometry}
        material={nodes.Sphere016.material}
        position={[0.0143, 0.0572, 0.0391]}
        rotation={[1.6085, -0.0477, 1.906]}
        scale={[0.0454, 0.1002, 0.0491]}
      />
      <mesh
        geometry={nodes.Sphere021.geometry}
        material={nodes.Sphere021.material}
        position={[-0.0318, 0.0555, 0.0397]}
        rotation={[1.2649, -0.0358, 1.9144]}
        scale={[0.0454, 0.1002, 0.0491]}
      />
      <mesh
        geometry={nodes.Sphere022.geometry}
        material={nodes.Sphere022.material}
        position={[-0.0537, 0.0534, 0.0205]}
        rotation={[1.7279, 0.4068, -1.5663]}
        scale={[0.0454, 0.1002, 0.0491]}
      />
      <mesh
        geometry={nodes.Sphere023.geometry}
        material={nodes.Sphere023.material}
        position={[-0.0613, 0.051, -0.0096]}
        rotation={[2.0709, 0.8564, 2.3878]}
        scale={[0.0454, 0.1002, 0.0491]}
      />
      <mesh
        geometry={nodes.Sphere025.geometry}
        material={nodes.Sphere025.material}
        position={[-0.0195, 0.0514, -0.0615]}
        rotation={[0.7126, 0.8441, -2.1582]}
        scale={[0.0454, 0.1002, 0.0491]}
      />
      <mesh
        geometry={nodes.Sphere030.geometry}
        material={nodes.Sphere030.material}
        position={[0.0465, 0.0569, -0.0333]}
        rotation={[1.8667, -0.332, -0.2065]}
        scale={[0.0454, 0.1002, 0.0491]}
      />
      <mesh
        geometry={nodes.Sphere031.geometry}
        material={nodes.Sphere031.material}
        position={[0.0386, 0.0576, -0.0258]}
        rotation={[1.6935, 0.0033, -0.7035]}
        scale={[0.0454, 0.1002, 0.0491]}
      />
      <mesh
        geometry={nodes.Sphere007.geometry}
        material={nodes.Sphere007.material}
        position={[0.0025, 0.0557, -0.038]}
        rotation={[1.9412, -0.2251, -1.2617]}
        scale={[0.0496, 0.069, 0.0537]}
      />
      <mesh
        geometry={nodes.Sphere011.geometry}
        material={nodes.Sphere011.material}
        position={[0.037, 0.0484, 0.049]}
        rotation={[2.6274, -0.2251, -0.0352]}
        scale={[0.0496, 0.069, 0.0537]}
      />
      <mesh
        geometry={nodes.Sphere012.geometry}
        material={nodes.Sphere012.material}
        position={[0.0371, 0.0524, 0.0143]}
        rotation={[0.9402, -0.2927, -1.6351]}
        scale={[0.0496, 0.069, 0.0537]}
      />
      <mesh
        geometry={nodes.Sphere018.geometry}
        material={nodes.Sphere018.material}
        position={[-0.0007, 0.0552, 0.0524]}
        rotation={[1.9281, 0.5918, 1.5601]}
        scale={[0.0496, 0.069, 0.0537]}
      />
      <mesh
        geometry={nodes.Sphere019.geometry}
        material={nodes.Sphere019.material}
        position={[-0.013, 0.0514, 0.027]}
        rotation={[1.3169, -0.5259, -0.6055]}
        scale={[0.0496, 0.069, 0.0537]}
      />
      <mesh
        geometry={nodes.Sphere024.geometry}
        material={nodes.Sphere024.material}
        position={[-0.0273, 0.0577, -0.0467]}
        rotation={[1.2685, 0.3568, 1.519]}
        scale={[0.0496, 0.069, 0.0537]}
      />
      <mesh
        geometry={nodes.Sphere028.geometry}
        material={nodes.Sphere028.material}
        position={[0.0206, 0.0572, -0.0457]}
        rotation={[1.7251, 0.0521, -1.0499]}
        scale={[0.0496, 0.069, 0.0537]}
      />
      <mesh
        geometry={nodes.Sphere013.geometry}
        material={nodes.Sphere013.material}
        position={[0.0251, 0.0558, 0.0274]}
        rotation={[1.4825, -0.413, -1.4443]}
        scale={[0.0408, 0.0577, 0.0442]}
      />
      <mesh
        geometry={nodes.Sphere026.geometry}
        material={nodes.Sphere026.material}
        position={[-0.0128, 0.0533, -0.0609]}
        rotation={[1.2045, -0.1072, 0.559]}
        scale={[0.0408, 0.0577, 0.0442]}
      />
      <mesh
        geometry={nodes.Sphere014.geometry}
        material={nodes.Sphere014.material}
        position={[0.0136, 0.0506, 0.0237]}
        rotation={[0.9256, -0.0847, 1.0407]}
        scale={[0.0499, 0.0862, 0.054]}
      />
      <mesh
        geometry={nodes.Sphere017.geometry}
        material={nodes.Sphere017.material}
        position={[-0.0023, 0.0532, 0.0297]}
        rotation={[1.267, 0.2241, 0.0785]}
        scale={[0.0499, 0.0862, 0.054]}
      />
      <mesh
        geometry={nodes.Sphere029.geometry}
        material={nodes.Sphere029.material}
        position={[0.024, 0.0554, -0.0317]}
        rotation={[1.5024, 0.7731, -2.1985]}
        scale={[0.0499, 0.0862, 0.054]}
      />
      <mesh
        geometry={nodes.Sphere010.geometry}
        material={nodes.Sphere010.material}
        position={[-0.0413, 0.0559, 0.0262]}
        rotation={[1.677, -0.0882, 0.5543]}
        scale={[0.0467, 0.103, 0.0505]}
      />
      <mesh
        geometry={nodes.Sphere020.geometry}
        material={nodes.Sphere020.material}
        position={[-0.0204, 0.0518, 0.0566]}
        rotation={[2.1481, 0.1266, -0.8958]}
        scale={[0.0467, 0.103, 0.0505]}
      />
      <mesh
        geometry={nodes.Sphere027.geometry}
        material={nodes.Sphere027.material}
        position={[-0.0007, 0.052, -0.0638]}
        rotation={[0.6671, 0.2835, -2.0979]}
        scale={[0.0467, 0.103, 0.0505]}
      />
      <mesh
        geometry={nodes.Sphere032.geometry}
        material={nodes.Sphere032.material}
        position={[0.0439, 0.0535, -0.0061]}
        rotation={[1.2292, -0.0212, -2.1821]}
        scale={[0.0467, 0.103, 0.0505]}
      />
    </group>
  )
}

useGLTF.preload('/donut48.gltf')
